language: cpp

os:
  - linux
  - osx

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt-5.11.3-xenial
      && sudo apt-get -qq update
      && sudo apt-get -qq install -y --force-yes g++-4.9 libc6-i386 freeglut3-dev liblz4-dev qt511tools qt511base qt511translations qt511imageformats
      && export CXX="g++-4.9"
      && export CC="gcc-4.9"
      ;
    else
         export HOMEBREW_NO_AUTO_UPDATE=1
      && export HOMEBREW_NO_INSTALL_CLEANUP=1
      && brew install freeglut qt5 lz4
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      QTDIR="/opt/qt511";
    else
      QTDIR="/usr/local/opt/qt5";
      export LIBRARY_PATH="$(brew --prefix lz4)/lib";
      export CPATH="$(brew --prefix lz4)/include";
    fi
  - export PATH="$QTDIR/bin:$PATH"
  - mkdir -p build
  - cd build
  - qmake -config release ..

script:
  - make -j2

before_deploy:
  - DEPLOY_DIR="deling-$(git describe --tags)-${TRAVIS_OS_NAME}64"
  - export DEPLOY_ARCHIVE="$DEPLOY_DIR.tar.gz"
  - mkdir -p "$DEPLOY_DIR"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         DEPLOY_BINARY="deling.app"
      && cp -r "$DEPLOY_BINARY" "$DEPLOY_DIR"
      && cp ../*.qm "$DEPLOY_DIR/$DEPLOY_BINARY/Contents/MacOS"
      && "$QTDIR/bin/macdeployqt" "$DEPLOY_DIR/$DEPLOY_BINARY"
      ;
    else
         cp deling "$DEPLOY_DIR"
      && cp ../*.qm "$DEPLOY_DIR"
      ;
    fi
  - tar -czf "$DEPLOY_ARCHIVE" "$DEPLOY_DIR"

deploy:
  provider: releases
  api_key:
    secure: BfRrMQnsLEn66poeALh/SfDkJf792r7RQ/fy+Zcagl2IFpGd3fsdpPtHtyNUJk0dWmJHdgyexSTgSrlfSmRAHt5ZP7fPfqwwvqi7M89l+jz5UsbvXOQX9iKuKa3ksrMXw0hoDyfLrSkwMLaMfCSNZ3prJhnswZl1zL1BH/nK4O8=
  file: "$DEPLOY_ARCHIVE"
  skip_cleanup: true
  on:
    tags: true
